Modified the version in requirement.txt file.
GoogleCloudPlatform/getting-started-python pull request #356
Opened 2021-06-02 08:17 UTC by harshapatel-tudip

Version Modified:
- Downgrade the google-cloud-logging version from 2.4.0 to 2.3.1.

2021-06-03 17:35 UTC, dandhlee commented
Thanks for this PR! Could you comment in the requirements file that we require it to be <2.4.0 for google-cloud-error-reporting 1.1.2? This was the from the dependency error message:
```
google-cloud-error-reporting 1.1.2 depends on google-cloud-logging<2.4 and >=1.14.0
```

Fixes #357

2021-06-03 17:37 UTC, dandhlee requested changes

2021-06-03 17:37 UTC, dandhlee commented on bookshelf/requirements.txt
> +google-cloud-logging==2.3.1
Please indicate that google-cloud-logging should be <2.4 and >=1.14.0 in a comment format.

2021-06-07 06:27 UTC, harshapatel-tudip commented
Closing this PR as as the issue for which the PR has been raised were fixed in the labs now.

2021-06-07 06:27 UTC, closed without merging